spring:
   profiles:
      active:
        - dev
---
server:
  port: 8201

spring:
  profiles: dev
  application:
      name: microconfig-test-client3

eureka:
 client:
  serviceUrl:
    defaultZone: http://admin:enjoy@localhost:7301/eureka
  register-with-eureka: false

info:
  app.name: microcloud-config-client-dev3
  company.name: enjoy3
---
server:
  port: 8102

spring:
  profiles: beta
  application:
      name: microconfig-test-client3

eureka:
 client:
  serviceUrl:
    defaultZone: http://admin:enjoy@localhost:7301/eureka
  register-with-eureka: false
  
info:
  app.name: microcloud-config-client-beta3
  company.name: enjoybeta3